services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=AIzaSxtyz1Xythg3p7gHBRdCRHpeZBQl_Iz-bbc
    volumes:
      - ./backend/chroma_db:/app/chroma_db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
